# Generated by Django 4.2 on 2026-09-27 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sessionops", "0030_class_section_school_academic_year"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportLog",
            fields=[
                (
                    "export_log_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "export_type",
                    models.CharField(
                        choices=[
                            ("school_children", "School children roster"),
                            ("school_volunteers", "School volunteer roster"),
                            ("school_timetable", "School timetable"),
                            ("schools_summary", "Schools summary"),
                            ("all_children", "All children in scope"),
                            ("all_volunteers", "All volunteers in scope"),
                            ("gap_report", "Ops gap report"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                (
                    "school_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                ("filters", models.JSONField(default=dict)),
                ("school_count", models.IntegerField(default=1)),
                ("row_count", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="sessionops.user",
                    ),
                ),
            ],
            options={
                "db_table": "export_log",
            },
        ),
        migrations.AddIndex(
            model_name="exportlog",
            index=models.Index(
                fields=["user_id", "created_at"], name="export_log_user_id_3a277d_idx"
            ),
        ),
    ]
