# Generated by Django 4.2 on 2026-09-28 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sessionops", "0031_export_log"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="class",
            options={"ordering": ["sequence", "class_code"]},
        ),
        migrations.AddField(
            model_name="class",
            name="next_class_id",
            field=models.ForeignKey(
                blank=True,
                db_column="next_class_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="previous_classes",
                to="sessionops.class",
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="open_for_enrolment",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="class",
            name="sequence",
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
