# Generated by Django 4.2 on 2026-09-29 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sessionops", "0034_one_active_school_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolholiday",
            name="school_academic_year_id",
            field=models.ForeignKey(
                blank=True,
                db_column="school_academic_year_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="sessionops.schoolacademicyear",
            ),
        ),
    ]
