# Generated by Django 4.2 on 2026-09-29 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sessionops", "0036_backfill_holiday_school_year"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgressionRun",
            fields=[
                ("run_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In progress"),
                            ("completed", "Completed"),
                            ("completed_with_failures", "Completed with failures"),
                        ],
                        default="in_progress",
                        max_length=30,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("cleanup", models.JSONField(default=dict)),
                (
                    "from_academic_year_id",
                    models.ForeignKey(
                        db_column="from_academic_year_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="sessionops.academicyear",
                    ),
                ),
                (
                    "started_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="sessionops.user",
                    ),
                ),
                (
                    "to_academic_year_id",
                    models.ForeignKey(
                        db_column="to_academic_year_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="sessionops.academicyear",
                    ),
                ),
            ],
            options={
                "db_table": "progression_run",
                "ordering": ["-run_id"],
            },
        ),
        migrations.CreateModel(
            name="SchoolProgression",
            fields=[
                (
                    "school_progression_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("school_id", models.BigIntegerField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("undone", "Undone"),
                            ("released", "Released"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("graduate_class_ids", models.JSONField(default=list)),
                ("graduate_child_ids", models.JSONField(default=list)),
                ("counts", models.JSONField(default=dict)),
                ("warnings", models.JSONField(default=list)),
                ("error", models.TextField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("undone_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "from_school_academic_year_id",
                    models.ForeignKey(
                        db_column="from_school_academic_year_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="sessionops.schoolacademicyear",
                    ),
                ),
                (
                    "run_id",
                    models.ForeignKey(
                        db_column="run_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="schools",
                        to="sessionops.progressionrun",
                    ),
                ),
                (
                    "to_school_academic_year_id",
                    models.ForeignKey(
                        blank=True,
                        db_column="to_school_academic_year_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="sessionops.schoolacademicyear",
                    ),
                ),
                (
                    "undone_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="sessionops.user",
                    ),
                ),
            ],
            options={
                "db_table": "school_progression",
            },
        ),
        migrations.CreateModel(
            name="ProgressionRowLog",
            fields=[
                ("row_log_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("table", models.CharField(max_length=50)),
                ("row_id", models.BigIntegerField()),
                ("source_row_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "action",
                    models.CharField(
                        choices=[("created", "Created"), ("archived", "Archived")],
                        max_length=10,
                    ),
                ),
                ("meta", models.JSONField(default=dict)),
                (
                    "school_progression_id",
                    models.ForeignKey(
                        db_column="school_progression_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="row_logs",
                        to="sessionops.schoolprogression",
                    ),
                ),
            ],
            options={
                "db_table": "progression_row_log",
            },
        ),
        migrations.AddIndex(
            model_name="schoolprogression",
            index=models.Index(
                fields=["school_id", "status"], name="school_prog_school__9b02bf_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="schoolprogression",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ("queued", "running", "failed"))),
                fields=("school_id",),
                name="uniq_unfinished_progression_per_school",
            ),
        ),
        migrations.AddIndex(
            model_name="progressionrowlog",
            index=models.Index(
                fields=["school_progression_id", "table"],
                name="progression_school__9df31f_idx",
            ),
        ),
    ]
