# Generated by Django 4.2 on 2026-09-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sessionops", "0037_progression_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="childremovallog",
            name="removed_reason",
            field=models.CharField(
                choices=[
                    ("inactive", "Inactive"),
                    ("duplicate_entry", "Duplicate entry"),
                    ("wrong_school_class", "Added to wrong school/class by mistake"),
                    ("transferred", "Transferred to another school"),
                    ("dropped_out", "Dropped out of school"),
                    ("family_declined", "Family does not want the child enrolled"),
                    ("child_declined", "Child no longer interested in participating"),
                    ("other", "Other"),
                    ("graduated", "Graduated"),
                ],
                max_length=20,
            ),
        ),
    ]
