# Generated by Django 4.2 on 2026-10-05 15:59

import django.db.models.deletion
from django.db import migrations, models


def backfill_school_targets(apps, schema_editor):
    """Runs before 2026-10-05 had one target per run; copy it onto each school."""
    SchoolProgression = apps.get_model("sessionops", "SchoolProgression")
    # Same connection as the migration: it holds the AddField lock on this table,
    # so a query on another connection would wait on it forever.
    db = schema_editor.connection.alias
    rows = (
        SchoolProgression.objects.using(db)
        .filter(to_academic_year_id__isnull=True)
        .select_related("run_id")
    )
    for sp in rows:  # save() goes back through the same alias
        if sp.run_id.to_academic_year_id_id:
            sp.to_academic_year_id_id = sp.run_id.to_academic_year_id_id
            sp.save(update_fields=["to_academic_year_id"])


class Migration(migrations.Migration):
    dependencies = [
        ("sessionops", "0039_derive_class_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolprogression",
            name="to_academic_year_id",
            field=models.ForeignKey(
                blank=True,
                db_column="to_academic_year_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="sessionops.academicyear",
            ),
        ),
        migrations.AlterField(
            model_name="progressionrun",
            name="from_academic_year_id",
            field=models.ForeignKey(
                blank=True,
                db_column="from_academic_year_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="sessionops.academicyear",
            ),
        ),
        migrations.AlterField(
            model_name="progressionrun",
            name="to_academic_year_id",
            field=models.ForeignKey(
                blank=True,
                db_column="to_academic_year_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="sessionops.academicyear",
            ),
        ),
        migrations.RunPython(backfill_school_targets, migrations.RunPython.noop),
    ]
